"""
Demo Mode Service
Provides mock AI responses and demo data for showcasing Martin-Coder
"""

import asyncio
import random
from typing import AsyncGenerator, Optional
from datetime import datetime

# Demo AI responses for different scenarios
DEMO_RESPONSES = {
    "default": """I understand you're asking about: {query}

Let me help you with that! Here's a comprehensive solution:

```python
# Example implementation
def solution():
    \"\"\"
    This is a demo response showcasing Martin-Coder's capabilities.
    In production, this would be generated by the actual AI model.
    \"\"\"
    pass
```

**Key points:**
1. This demonstrates real-time AI assistance
2. Code is syntax-highlighted and formatted
3. Responses include explanations and best practices

Would you like me to elaborate on any specific part?""",

    "create": """I'll create that for you! Here's the implementation:

```{language}
{code}
```

**What this code does:**
- Implements the requested functionality
- Follows best practices and conventions
- Includes proper error handling
- Is well-documented

**Files created/modified:**
- `{filename}` - Main implementation

Would you like me to add tests or documentation?""",

    "explain": """Let me explain this code:

**Overview:**
This code implements {topic} using a clean, maintainable approach.

**Key Components:**

1. **Structure**: The code is organized into logical sections
2. **Patterns**: Uses {pattern} pattern for better maintainability
3. **Error Handling**: Includes proper exception handling
4. **Performance**: Optimized for efficiency

**Step-by-step breakdown:**
1. First, it initializes the necessary components
2. Then, it processes the input data
3. Finally, it returns the formatted result

Is there a specific part you'd like me to elaborate on?""",

    "fix": """I've identified the issue and here's the fix:

**Problem:**
{problem}

**Solution:**
```{language}
{fix_code}
```

**Why this works:**
- Addresses the root cause of the issue
- Follows best practices
- Includes proper validation

**Prevention:**
To prevent similar issues in the future:
1. Add input validation
2. Include error handling
3. Write unit tests

The fix has been applied. Would you like me to explain anything else?""",

    "optimize": """Here's the optimized version:

**Before (O(n²)):**
```{language}
{before_code}
```

**After (O(n)):**
```{language}
{after_code}
```

**Improvements:**
- ⚡ 10x faster execution
- 📉 50% less memory usage
- ✅ Better maintainability

**Benchmark Results:**
| Metric | Before | After |
|--------|--------|-------|
| Time   | 500ms  | 50ms  |
| Memory | 100MB  | 50MB  |

Would you like me to apply these optimizations?"""
}

# Sample code snippets for demo
SAMPLE_CODES = {
    "python": {
        "api": '''from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List

app = FastAPI()

class Item(BaseModel):
    name: str
    price: float

items: List[Item] = []

@app.get("/items")
def get_items():
    return items

@app.post("/items")
def create_item(item: Item):
    items.append(item)
    return item''',

        "class": '''class DataProcessor:
    """Process and transform data efficiently."""

    def __init__(self, config: dict):
        self.config = config
        self._cache = {}

    def process(self, data: list) -> list:
        """Process input data and return results."""
        results = []
        for item in data:
            if item not in self._cache:
                self._cache[item] = self._transform(item)
            results.append(self._cache[item])
        return results

    def _transform(self, item):
        """Transform a single item."""
        return item.upper() if isinstance(item, str) else item''',

        "async": '''import asyncio
from typing import List

async def fetch_data(url: str) -> dict:
    """Fetch data from URL asynchronously."""
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            return await response.json()

async def fetch_all(urls: List[str]) -> List[dict]:
    """Fetch multiple URLs concurrently."""
    tasks = [fetch_data(url) for url in urls]
    return await asyncio.gather(*tasks)'''
    },

    "typescript": {
        "component": '''import React, { useState, useEffect } from 'react';

interface Props {
  title: string;
  onSubmit: (data: FormData) => void;
}

export function Form({ title, onSubmit }: Props) {
  const [data, setData] = useState<FormData>({});
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await onSubmit(data);
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <h2>{title}</h2>
      {/* Form fields */}
      <button disabled={loading}>
        {loading ? 'Submitting...' : 'Submit'}
      </button>
    </form>
  );
}''',

        "hook": '''import { useState, useCallback, useEffect } from 'react';

export function useApi<T>(url: string) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(url);
      const result = await response.json();
      setData(result);
    } catch (e) {
      setError(e as Error);
    } finally {
      setLoading(false);
    }
  }, [url]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return { data, loading, error, refetch: fetchData };
}'''
    }
}


class DemoProvider:
    """Demo AI provider for showcasing capabilities."""

    name = "demo"
    display_name = "Demo Mode"

    def __init__(self):
        self.typing_speed = 0.02  # Seconds per character for streaming

    async def chat(
        self,
        messages: list,
        model: str = "demo-model",
        temperature: float = 0.7,
        tools: Optional[list] = None,
    ) -> dict:
        """Generate a demo response."""
        # Get the last user message
        user_message = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                user_message = msg.get("content", "")
                break

        response_text = self._generate_response(user_message)

        return {
            "id": f"demo-{datetime.now().timestamp()}",
            "model": model,
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": response_text
                    },
                    "finish_reason": "stop"
                }
            ],
            "usage": {
                "prompt_tokens": len(user_message.split()),
                "completion_tokens": len(response_text.split()),
                "total_tokens": len(user_message.split()) + len(response_text.split())
            }
        }

    async def stream_chat(
        self,
        messages: list,
        model: str = "demo-model",
        temperature: float = 0.7,
        tools: Optional[list] = None,
    ) -> AsyncGenerator[dict, None]:
        """Stream a demo response character by character."""
        # Get the last user message
        user_message = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                user_message = msg.get("content", "")
                break

        response_text = self._generate_response(user_message)

        # Stream response
        for i, char in enumerate(response_text):
            yield {
                "choices": [
                    {
                        "delta": {"content": char},
                        "finish_reason": None
                    }
                ]
            }
            await asyncio.sleep(self.typing_speed)

        # Final message
        yield {
            "choices": [
                {
                    "delta": {},
                    "finish_reason": "stop"
                }
            ]
        }

    def _generate_response(self, query: str) -> str:
        """Generate appropriate response based on query."""
        query_lower = query.lower()

        # Detect intent
        if any(word in query_lower for word in ["create", "make", "build", "generate", "write"]):
            template = DEMO_RESPONSES["create"]
            language = "python" if "python" in query_lower else "typescript"
            code_type = "api" if "api" in query_lower else "class"
            code = SAMPLE_CODES.get(language, {}).get(code_type, SAMPLE_CODES["python"]["class"])
            return template.format(
                language=language,
                code=code,
                filename="main.py" if language == "python" else "index.tsx"
            )

        elif any(word in query_lower for word in ["explain", "what", "how", "why"]):
            template = DEMO_RESPONSES["explain"]
            return template.format(
                topic="the requested functionality",
                pattern="Factory"
            )

        elif any(word in query_lower for word in ["fix", "bug", "error", "issue", "problem"]):
            template = DEMO_RESPONSES["fix"]
            return template.format(
                problem="The identified issue has been analyzed",
                language="python",
                fix_code="# Fixed implementation\ndef fixed_function():\n    return 'Fixed!'"
            )

        elif any(word in query_lower for word in ["optimize", "improve", "faster", "performance"]):
            template = DEMO_RESPONSES["optimize"]
            return template.format(
                language="python",
                before_code="# Slow version\nfor i in items:\n    for j in items:\n        process(i, j)",
                after_code="# Fast version\nfrom collections import defaultdict\nprocessed = defaultdict(list)\nfor item in items:\n    processed[item.key].append(item)"
            )

        else:
            return DEMO_RESPONSES["default"].format(query=query[:100])

    async def list_models(self) -> list:
        """Return demo models."""
        return [
            {
                "id": "demo-model",
                "name": "Demo Model",
                "context_window": 100000,
                "max_output": 4096,
                "description": "Demo model for showcasing Martin-Coder"
            },
            {
                "id": "demo-fast",
                "name": "Demo Fast",
                "context_window": 50000,
                "max_output": 2048,
                "description": "Faster demo responses"
            }
        ]


# Singleton instance
demo_provider = DemoProvider()


def is_demo_mode() -> bool:
    """Check if application is running in demo mode."""
    import os
    return os.environ.get("DEMO_MODE", "").lower() == "true"


def get_demo_provider() -> DemoProvider:
    """Get the demo provider instance."""
    return demo_provider
